---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp-bridge
  labels:
    app: idp-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idp-bridge
  template:
    metadata:
      labels:
        app: idp-bridge
    spec:
      containers:
        - name: idp-bridge
          image: docker.stackable.tech/gaia-x/idp-bridge:0.1.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DEPLOYMENT_ENVIRONMENT
              value: ccmc
            - name: SERVER_BASE-URL
              value: https://idp-bridge.{{.Values.domain}}
            - name: SSI_VERIFIER_BASE-URL
              value: https://idp-bridge.{{.Values.domain}}
            - name: SSI_VERIFIER_FAILED-URL
              value: https://idp-bridge.{{.Values.domain}}
            - name: SSI_VERIFIER_SUCCESS-URL
              value: https://idp-bridge.{{.Values.domain}}/openid4vp/continue
            - name: SSI_WALLET_BASE-URL
              value: https://wallet.{{.Values.domain}}/
            - name: DATASOURCE_URL
              value: jdbc:h2:file:/app/data/db
          volumeMounts:
          - name: idp-bridge-h2-data
            mountPath: /app/data
      volumes:
        - name: idp-bridge-h2-data
          persistentVolumeClaim:
            claimName: idp-bridge-h2-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: idp-bridge-h2-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: idp-bridge
  labels:
    app: idp-bridge
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: idp-bridge
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: idp-bridge
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - idp-bridge.{{.Values.domain}}
    secretName: ingress-idp-bridge
  rules:
    - host: idp-bridge.{{.Values.domain}}
      http:
        paths:
          - backend:
              service:
                name: idp-bridge # The target service name
                port:
                  number: 8080 # And the target port as declared inside the service
            path: / # No path routing here, just use the Host Header. You can combine multiple Hosts / pathPrefixes
            pathType: Prefix
