apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-portal-config
data:
  .env: |
    {{- if .Values.tls.enabled }}
    NEXT_PUBLIC_VC_REPO: https://credentials.{{.Values.domain}}
    NEXT_PUBLIC_ISSUER: https://issuer.{{.Values.domain}}
    NEXT_PUBLIC_VERIFIER: https://verifier.{{.Values.domain}}
    NEXT_PUBLIC_WALLET: https://wallet.{{.Values.domain}}
    {{- else }}
    NEXT_PUBLIC_VC_REPO: http://credentials.{{.Values.domain}}
    NEXT_PUBLIC_ISSUER: http://issuer.{{.Values.domain}}
    NEXT_PUBLIC_VERIFIER: http://verifier.{{.Values.domain}}
    NEXT_PUBLIC_WALLET: http://wallet.{{.Values.domain}}
    {{- end }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-portal
  template:
    metadata:
      labels:
        app: web-portal
    spec:
      containers:
        - name: web-portal
          image: waltid/portal:0.7.0
          env:
            {{- if .Values.tls.enabled }}
            - name: NEXT_PUBLIC_VC_REPO
              value: "https://credentials.{{.Values.domain}}"
            - name: NEXT_PUBLIC_ISSUER
              value: "https://issuer.{{.Values.domain}}"
            - name: NEXT_PUBLIC_VERIFIER
              value: "https://verifier.si.stackable.tech"
            - name: NEXT_PUBLIC_WALLET
              value: "https://wallet.{{.Values.domain}}"
            {{- else }}
            - name: NEXT_PUBLIC_VC_REPO
              value: "http://credentials.{{.Values.domain}}"
            - name: NEXT_PUBLIC_ISSUER
              value: "http://issuer.{{.Values.domain}}"
            - name: NEXT_PUBLIC_VERIFIER
              value: "http://verifier.si.stackable.tech"
            - name: NEXT_PUBLIC_WALLET
              value: "http://wallet.{{.Values.domain}}"
            {{- end }}
          ports:
            - containerPort: 3000
              name: http-portal
          volumeMounts:
            - mountPath: /app/.env
              subPath: ".env"
              name: wallet-portal-config
              readOnly: true
      hostAliases:
        {{- toYaml .Values.hostAliases | nindent 6 }}
      volumes:
        - name: wallet-portal-config
          configMap:
            name: wallet-portal-config
---
kind: Service
apiVersion: v1
metadata:
  name: web-portal
spec:
  ports:
    - name: http
      port: 80
      targetPort: http-portal
      protocol: TCP
  selector:
    app: web-portal
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - portal.{{.Values.domain}}
      secretName: ingress-portal
  {{- end }}
  rules:
    - host: portal.{{.Values.domain}}
      http:
        paths:
          - path: /offer
            pathType: Prefix
            backend:
              service:
                name: issuer
                port:
                  number: 80
          - path: /verify
            pathType: Prefix
            backend:
              service:
                name: verifier
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-portal
                port:
                  name: http
