kind: Deployment
apiVersion: apps/v1
metadata:
  name: vc-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vc-repo
  template:
    metadata:
      labels:
        app: vc-repo
    spec:
      containers:
        - name: vc-repo
          image: waltid/vc-repository:1.2409171123.0
          env:
          - name: PORT
            value: "7103"
          ports:
            - containerPort: 7103
              name: http-api
---
kind: Service
apiVersion: v1
metadata:
  name: vc-repo
spec:
  ports:
    - name: http
      port: 80
      targetPort: http-api
      protocol: TCP
  selector:
    app: vc-repo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vc-repo
spec:
  ingressClassName: nginx
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - credentials.{{.Values.domain}}
      secretName: ingress-credentials
  {{- end }}
  rules:
    - host: credentials.{{.Values.domain}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vc-repo
                port:
                  name: http
